[package]
name = "example_multiple_windows"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bevy = { version = "0.12.0", default_features = false }
bevy_pixels = { path = "../../" }
