[package]
name = "example_bounce"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
bevy = { version = "0.15", default-features = false }
bevy_pixels = { path = "../../" }
rand = "0.8"
